### PR TITLE
Merge review

### LINKED ISSUE #7: 4. På samma sida ska det vara möjligt att skicka in en egen recension, där man anger betyg samt sitt namn, och skriver en valfri kommentar. Formuläret ska skickas utan att sidan laddas om, d.v.s. med hjälp av webbläsarens fetch()

### PR DESCRIPTION
**Pull request by matodorovic**

### CODE REVIEW

**Review by emmaambr — COMMENTED** [review]
Great job. As of right now, I can only see a total of 25 reviews per movie, and therefor i can't see my own reviews. If thats a requirement maybe we should fix it?

**Comment by Nw84** [comment]
> Great job. As of right now, I can only see a total of 25 reviews per movie, and therefor i can't see my own reviews. If thats a requirement maybe we should fix it?

I will fix it 👍

**Comment by emmaambr** [comment]
> > Great job. As of right now, I can only see a total of 25 reviews per movie, and therefor i can't see my own reviews. If thats a requirement maybe we should fix it?
> 
> I will fix it 👍

Perfect 👍🏻

**Review by emmaambr — APPROVED** [review]

**Review by mhema42 — APPROVED** [review]
Looks fine

**Pull request merged**
